name: nodelabs_case_main
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  go_router: ^14.6.2
  flutter_screenutil: ^5.9.3
  
  # State Management
  flutter_bloc: ^8.1.6
  
  # Network & API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  
  # Local Storage
  shared_preferences: ^2.2.3
  
  # Image Handling
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  
  # Utils
  equatable: ^2.0.5
  
  # Animations
  lottie: ^3.1.2
  
  # Localization
  intl: ^0.19.0
  
  # File handling
  path_provider: ^2.1.4
  
  # Database
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true

  assets:
    # Görseller
    - assets/images/
    - assets/images/anasayfa.jpg
    - assets/images/icon.svg
    - assets/images/Shine Effect.svg
    
    

    # İkonlar
    - assets/icons/
    - assets/icons/navbar/
    - assets/icons/icon/Component/Components/
    - assets/icons/fav_button/
    - assets/icons/button/
    - assets/icons/coin_options/
    - assets/icons/liked_cards/
    - assets/icons/upload/
    - assets/icons/input/

    # Animasyonlar
    - assets/animations/

# Native splash configuration
flutter_native_splash:
  color: "#000000"
  android_12:
    color: "#000000"
  android: true
  ios: true
